# AI research power intelligent system

Problem  - get help to find the relevant paper

solution - semantic meaning search

steps -
1. data collection
2. Text extraction
3. nlp preprocessig and creation of embedding
4. implement sentence transformers
5. embedding store that is vector database
6. Semantic search
7. generate output

In [1]:
!pip install datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.7.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.36.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.5.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.6.17)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [2]:
from datasets import load_dataset

In [3]:
dataset = load_dataset("CShorten/ML-ArXiv-Papers", split="train")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

In [4]:

print(dataset)

Dataset({
    features: ['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'],
    num_rows: 117592
})

In [5]:
dataset[0]

{'Unnamed: 0.1': 0,
 'Unnamed: 0': 0.0,
 'title': 'Learning from compressed observations',
 'abstract': '  The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rate functions. The ideas are\nillustrated on the example of nonparametric regression in Gaussian noise.\n'}

In [6]:
import pandas as pd

In [7]:
df = pd.DataFrame(dataset)
df

,Unnamed: 0.1,Unnamed: 0,title,abstract
0,0,0.0,Learning from compressed observations,The problem of statistical learning is to co...
1,1,1.0,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,2,2.0,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,3,3.0,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,4,4.0,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...,...,...
117587,4995,NaN,Detecting COVID-19 Conspiracy Theories with Tr...,The sharing of fake news and conspiracy theori...
117588,4996,NaN,Fair Feature Subset Selection using Multiobjec...,The feature subset selection problem aims at s...
117589,4997,NaN,A Simple Duality Proof for Wasserstein Distrib...,We present a short and elementary proof of the...
117590,4998,NaN,Combined Learning of Neural Network Weights fo...,"We introduce CoLN, Combined Learning of Neural..."
117591,4999,NaN,Adapting and Evaluating Influence-Estimation M...,Influence estimation analyzes how changes to t...

In [8]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'], dtype='object')

In [9]:
df = df[['title','abstract']]

In [10]:
df

,title,abstract
0,Learning from compressed observations,The problem of statistical learning is to co...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...
117587,Detecting COVID-19 Conspiracy Theories with Tr...,The sharing of fake news and conspiracy theori...
117588,Fair Feature Subset Selection using Multiobjec...,The feature subset selection problem aims at s...
117589,A Simple Duality Proof for Wasserstein Distrib...,We present a short and elementary proof of the...
117590,Combined Learning of Neural Network Weights fo...,"We introduce CoLN, Combined Learning of Neural..."
117591,Adapting and Evaluating Influence-Estimation M...,Influence estimation analyzes how changes to t...

In [11]:
df.shape

(117592, 2)

In [12]:
df = df.head(15000)

In [13]:
df.shape

(15000, 2)

In [14]:
df.isnull().sum()

title       0
abstract    0
dtype: int64

In [15]:
df["paper_text"]=df["title"]+" "+df["abstract"]

/tmp/ipykernel_3436/529180721.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["paper_text"]=df["title"]+" "+df["abstract"]

In [16]:
df[["paper_text"]].head()

                                          paper_text
0  Learning from compressed observations   The pr...
1  Sensor Networks with Random Links: Topology De...
2  The on-line shortest path problem under partia...
3  A neural network approach to ordinal regressio...
4  Parametric Learning and Monte Carlo Optimizati...

In [17]:
type(df[["paper_text"]].head())

pandas.core.frame.DataFrame

In [18]:
df[["paper_text"]].head()

                                          paper_text
0  Learning from compressed observations   The pr...
1  Sensor Networks with Random Links: Topology De...
2  The on-line shortest path problem under partia...
3  A neural network approach to ordinal regressio...
4  Parametric Learning and Monte Carlo Optimizati...

In [19]:
print(df["paper_text"].iloc[0])

Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random
variable $Y$ as a function of a related random variable $X$ on the basis of an
i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable
predictors are drawn from some specified class, and the goal is to approach
asymptotically the performance (expected loss) of the best predictor in the
class. We consider the setting in which one has perfect observation of the
$X$-part of the sample, while the $Y$-part has to be communicated at some
finite bit rate. The encoding of the $Y$-values is allowed to depend on the
$X$-values. Under suitable regularity conditions on the admissible predictors,
the underlying family of probability distributions and the loss function, we
give an information-theoretic characterization of achievable predictor
performance in terms of conditional distortion-rate functions. The ideas are
illustrated on the example of nonparametric regression in Gaussian noise.

In [20]:
from sentence_transformers import SentenceTransformer

The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.

0it [00:00, ?it/s]

WARNING:torchao.kernel.intmm:Warning: Detected no triton, on systems without Triton certain kernels will not work

In [21]:
model = SentenceTransformer("all-MiniLM-L6-v2")

In [22]:
print(type(model))

<class 'sentence_transformers.sentence_transformer.model.SentenceTransformer'>

In [23]:
df["paper_text"].fillna("").astype(str).str.replace("\n", " ", regex=False)
df["paper_text"]=df["paper_text"].str.strip()

/tmp/ipykernel_3436/823472429.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["paper_text"]=df["paper_text"].str.strip()

In [24]:
sample_text=df["paper_text"].iloc[0]
sample_text

'Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rate functions. The ideas are\nillustrated on the example of nonparametric regression in Gaussian noise.'

In [25]:
embedding=model.encode(sample_text)
print(type(embedding))
print(embedding.shape)

<class 'numpy.ndarray'>
(384,)

In [26]:
embedding[:56]

array([-0.1315641 , -0.00678266, -0.00367612,  0.03265158,  0.11219642,
        0.01227267,  0.09816719, -0.0900523 ,  0.04231161, -0.01977348,
       -0.03308417,  0.07452948,  0.10632038, -0.02060429, -0.02052106,
        0.00169493,  0.07081953,  0.05854454, -0.11231912,  0.02082474,
        0.05692544,  0.0201578 ,  0.0258311 ,  0.0321703 ,  0.10513764,
       -0.09676763,  0.02700802, -0.0234509 , -0.04549678, -0.01013699,
       -0.01794855, -0.04814427,  0.01077652, -0.03759069,  0.01943481,
        0.03715189,  0.02967844,  0.04330941,  0.04373213,  0.03704866,
       -0.00182594,  0.00455183, -0.00799067,  0.03037368, -0.014378  ,
        0.03795147,  0.0595916 , -0.02583356, -0.06521576,  0.05900268,
       -0.02107134,  0.07359422, -0.05720106,  0.00294061,  0.00767515,
       -0.0333416 ], dtype=float32)

In [27]:
sample_embedding=model.encode(df["paper_text"].head(5).to_list())

In [28]:
print(sample_embedding.shape)

(5, 384)

In [29]:
from sklearn.metrics.pairwise import cosine_similarity

In [30]:
similarity = cosine_similarity(sample_embedding[0].reshape(1,-1),
                               sample_embedding[1].reshape(1, -1))
print(similarity)

[[0.36625272]]

In [31]:
similarity = cosine_similarity(sample_embedding[1].reshape(1,-1),
                               sample_embedding[1].reshape(1, -1))
print(similarity)

[[1.]]

In [32]:
for i in range(1, 5):
  sim=cosine_similarity(sample_embedding[0].reshape(1,-1),
                               sample_embedding[i].reshape(1, -1))
  print(sim)

[[0.36625272]]
[[0.33522844]]
[[0.15505108]]
[[0.37421533]]

# generate full embedding

In [33]:
import numpy as np

In [34]:
import os
import numpy as np
if os.path.exists("embedding.npy"):
    print("Loading saved embeddings")
    embedding = np.load("embedding.npy")
else:
    print("Generating embeddings")
    embedding = model.encode(
        df["paper_text"].tolist(),
        batch_size=32,
        show_progress_bar=True
    )
    np.save("embedding.npy", embedding)
    print("Embeddings saved successfully!")

Loading saved embeddings

In [35]:
print(embedding.shape)
print(type(embedding))

(15000, 384)
<class 'numpy.ndarray'>

In [36]:
embedding.dtype

dtype('float32')

In [37]:
!pip install faiss-cpu
import faiss

Requirement already satisfied: faiss-cpu in /usr/local/lib/python3.12/dist-packages (1.14.3)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.2)

In [38]:
if os.path.exists("paper_faiss.index"):
    print("Loading existing FAISS index")
    index = faiss.read_index("paper_faiss.index")
else:
    print("Creating new FAISS index")
    faiss.normalize_L2(embedding)
    index = faiss.IndexFlatIP(384)
    index.add(embedding)
    faiss.write_index(index, "paper_faiss.index")
    print("FAISS index saved successfully!")

Loading existing FAISS index

In [39]:
query="deep learning for medical image analysis"
query_embedding= model.encode([query])
query_embedding.shape

(1, 384)

In [40]:
faiss.normalize_L2(query_embedding)

In [41]:
D,I = index.search(query_embedding,5)
print(D)
print(I)

[[0.6807244  0.67092204 0.65219975 0.62811744 0.61311525]]
[[10466 13730 11873 12691 11282]]

In [42]:
def search_paper(query, k=5):
  query_embedding = model.encode([query])
  faiss.normalize_L2(query_embedding)
  D, I = index.search(query_embedding, k)
  for score, idx in zip(D[0], I[0]):
    print("Similarity score", score)
    print("Title", df.iloc[idx]["title"][:500])

search_paper("deep learning for medical image analysis")

Similarity score 0.6807244
Title A Perspective on Deep Imaging
Similarity score 0.67092204
Title Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?
Similarity score 0.65219975
Title Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection
Similarity score 0.62811744
Title High-Resolution Breast Cancer Screening with Multi-View Deep
  Convolutional Neural Networks
Similarity score 0.61311525
Title Deep Learning for the Classification of Lung Nodules

In [43]:
print(df.iloc[10466]["title"])

A Perspective on Deep Imaging

In [44]:
print(df.iloc[10466]["abstract"])

  The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance in clinical and
preclinical applications. To realize the full impact of machine learning on
medical imaging, major challenges must be addressed.

In [45]:
print(df.iloc[11873]["title"])

Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection

In [46]:
def search_paper(query,k=5):
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  return D,I

In [47]:
D,I= search_paper("deep learning for medical image analysis")
print(D)
print(I)

[[0.6807244  0.67092204 0.65219975 0.62811744 0.61311525]]
[[10466 13730 11873 12691 11282]]

In [48]:
def search_paper(query,k=5):
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  for score,idx in zip(D[0],I[0]):
    print("Similarity score",score)
    print("Title",df.iloc[idx]["title"])
    print("Title",df.iloc[idx]["abstract"][:500])
    print()

In [49]:
search_paper("deep learning for medical image analysis")

Similarity score 0.6807244
Title A Perspective on Deep Imaging
Title   The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance

Similarity score 0.67092204
Title Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?
Title   Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure proper convergence. A promising alternative is to fine-tune
a CNN that has been pre-trained using, for instance, a large set of labeled
natural images. However, the substantial differences between natural and
medical images may advise against such knowledge transfer. In this paper, we
seek to answer the following centra

Similarity score 0.65219975
Title Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection
Title   The classification of MRI images according to the anatomical field of view is
a necessary task to solve when faced with the increasing quantity of medical
images. In parallel, advances in deep learning makes it a suitable tool for
computer vision problems. Using a common architecture (such as AlexNet)
provides quite good results, but not sufficient for clinical use. Improving the
model is not an easy task, due to the large number of hyper-parameters
governing both the architecture and the trai

Similarity score 0.62811744
Title High-Resolution Breast Cancer Screening with Multi-View Deep
  Convolutional Neural Networks
Title   Advances in deep learning for natural images have prompted a surge of
interest in applying similar techniques to medical images. The majority of the
initial attempts focused on replacing the input of a deep convolutional neural
network with a medical image, which does not take into consideration the
fundamental differences between these two types of images. Specifically, fine
details are necessary for detection in medical images, unlike in natural images
where coarse structures matter most. Th

Similarity score 0.61311525
Title Deep Learning for the Classification of Lung Nodules
Title   Deep learning, as a promising new area of machine learning, has attracted a
rapidly increasing attention in the field of medical imaging. Compared to the
conventional machine learning methods, deep learning requires no hand-tuned
feature extractor, and has shown a superior performance in many visual object
recognition applications. In this study, we develop a deep convolutional neural
network (CNN) and apply it to thoracic CT images for the classification of lung
nodules. We present the CNN ar

In [50]:
!pip install transformers==4.46.3

Requirement already satisfied: transformers==4.46.3 in /usr/local/lib/python3.12/dist-packages (4.46.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (3.29.4)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (0.36.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (2.32.4)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (0.20.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (0.8.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.46.3) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.46.3) (1.5.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.46.3) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (2026.6.17)

In [51]:
from transformers import pipeline
summarizer = pipeline(
    "summarization",
    model="facebook/bart-large-cnn"

)

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [52]:
type(summarizer)

transformers.pipelines.text2text_generation.SummarizationPipeline

In [53]:
summary=summarizer(df.iloc[10466]["abstract"],max_length=120,min_length=40)
print(summary)

[{'summary_text': 'The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.'}]

In [54]:
type(summary)

list

In [55]:
type(summary[0])

dict

In [56]:
summary[0]["summary_text"]

'The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.'

In [57]:
for score, idx in zip(D[0],I[0]):
  print("Similarity score",score)
  print("Title",df.iloc[idx]["title"])
  print("Title",df.iloc[idx]["abstract"][:500])

  summary=summarizer(df.iloc[idx]["abstract"],max_length=120,min_length=40)
  print(summary)
  print(summary[0]["summary_text"])
  print()

Similarity score 0.6807244
Title A Perspective on Deep Imaging
Title   The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance
[{'summary_text': 'The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.'}]
The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.

Similarity score 0.67092204
Title Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?
Title   Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure proper convergence. A promising alternative is to fine-tune
a CNN that has been pre-trained using, for instance, a large set of labeled
natural images. However, the substantial differences between natural and
medical images may advise against such knowledge transfer. In this paper, we
seek to answer the following centra
[{'summary_text': 'Training a deep convolutional neural network from scratch is difficult because it requires a large amount of labeled training data. A promising alternative is to fine-tune a CNN that has been pre-trained using, for instance, a large set of labeled natural images.'}]
Training a deep convolutional neural network from scratch is difficult because it requires a large amount of labeled training data. A promising alternative is to fine-tune a CNN that has been pre-trained using, for instance, a large set of labeled natural images.

Similarity score 0.65219975
Title Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection
Title   The classification of MRI images according to the anatomical field of view is
a necessary task to solve when faced with the increasing quantity of medical
images. In parallel, advances in deep learning makes it a suitable tool for
computer vision problems. Using a common architecture (such as AlexNet)
provides quite good results, but not sufficient for clinical use. Improving the
model is not an easy task, due to the large number of hyper-parameters
governing both the architecture and the trai
[{'summary_text': 'The classification of MRI images according to the anatomical field of view is a necessary task to solve when faced with the increasing quantity of medical images. Using a common architecture (such as AlexNet) provides quite good results, but not sufficient for clinical use.'}]
The classification of MRI images according to the anatomical field of view is a necessary task to solve when faced with the increasing quantity of medical images. Using a common architecture (such as AlexNet) provides quite good results, but not sufficient for clinical use.

Similarity score 0.62811744
Title High-Resolution Breast Cancer Screening with Multi-View Deep
  Convolutional Neural Networks
Title   Advances in deep learning for natural images have prompted a surge of
interest in applying similar techniques to medical images. The majority of the
initial attempts focused on replacing the input of a deep convolutional neural
network with a medical image, which does not take into consideration the
fundamental differences between these two types of images. Specifically, fine
details are necessary for detection in medical images, unlike in natural images
where coarse structures matter most. Th
[{'summary_text': 'The study used a set of high-resolution images to test the accuracy of the neural network. It found that the network performed better than expected when it was given a large set of images to work with.'}]
The study used a set of high-resolution images to test the accuracy of the neural network. It found that the network performed better than expected when it was given a large set of images to work with.

Similarity score 0.61311525
Title Deep Learning for the Classification of Lung Nodules
Title   Deep learning, as a promising new area of machine learning, has attracted a
rapidly increasing attention in the field of medical imaging. Compared to the
conventional machine learning methods, deep learning requires no hand-tuned
feature extractor, and has shown a superior performance in many visual object
recognition applications. In this study, we develop a deep convolutional neural
network (CNN) and apply it to thoracic CT images for the classification of lung
nodules. We present the CNN ar
[{'summary_text': 'Deep learning, as a promising new area of machine learning, has attracted a rapidly increasing attention in the field of medical imaging. In this study, we develop a deep convolutional neuralnetwork (CNN) and apply it to thoracic CT images for the classification of lung nodules.'}]
Deep learning, as a promising new area of machine learning, has attracted a rapidly increasing attention in the field of medical imaging. In this study, we develop a deep convolutional neuralnetwork (CNN) and apply it to thoracic CT images for the classification of lung nodules.

In [58]:
def search_and_summarize(query,k=5):
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  for score,idx in zip(D[0],I[0]):
    print("Similarity score",score)
    print("Title",df.iloc[idx]["title"])
    print("Title",df.iloc[idx]["abstract"][:500])
    print()

    summary=summarizer(df.iloc[idx]["abstract"],max_length=120,min_length=40, do_sample=False)
    print(summary)
    print(summary[0]["summary_text"])
    print()

In [59]:
search_and_summarize("Deep learning in medical imaging",k=5)

Similarity score 0.73549855
Title A Perspective on Deep Imaging
Title   The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance

[{'summary_text': 'The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.'}]
The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.

Similarity score 0.6881736
Title Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection
Title   The classification of MRI images according to the anatomical field of view is
a necessary task to solve when faced with the increasing quantity of medical
images. In parallel, advances in deep learning makes it a suitable tool for
computer vision problems. Using a common architecture (such as AlexNet)
provides quite good results, but not sufficient for clinical use. Improving the
model is not an easy task, due to the large number of hyper-parameters
governing both the architecture and the trai

[{'summary_text': 'The classification of MRI images according to the anatomical field of view is a necessary task to solve when faced with the increasing quantity of medical images. Using a common architecture (such as AlexNet) provides quite good results, but not sufficient for clinical use.'}]
The classification of MRI images according to the anatomical field of view is a necessary task to solve when faced with the increasing quantity of medical images. Using a common architecture (such as AlexNet) provides quite good results, but not sufficient for clinical use.

Similarity score 0.6532082
Title Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?
Title   Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure proper convergence. A promising alternative is to fine-tune
a CNN that has been pre-trained using, for instance, a large set of labeled
natural images. However, the substantial differences between natural and
medical images may advise against such knowledge transfer. In this paper, we
seek to answer the following centra

[{'summary_text': 'Training a deep convolutional neural network from scratch is difficult because it requires a large amount of labeled training data. A promising alternative is to fine-tune a CNN that has been pre-trained using, for instance, a large set of labeled natural images.'}]
Training a deep convolutional neural network from scratch is difficult because it requires a large amount of labeled training data. A promising alternative is to fine-tune a CNN that has been pre-trained using, for instance, a large set of labeled natural images.

Similarity score 0.62220883
Title High-Resolution Breast Cancer Screening with Multi-View Deep
  Convolutional Neural Networks
Title   Advances in deep learning for natural images have prompted a surge of
interest in applying similar techniques to medical images. The majority of the
initial attempts focused on replacing the input of a deep convolutional neural
network with a medical image, which does not take into consideration the
fundamental differences between these two types of images. Specifically, fine
details are necessary for detection in medical images, unlike in natural images
where coarse structures matter most. Th

[{'summary_text': 'The study used a set of high-resolution images to test the accuracy of the neural network. It found that the network performed better than expected when it was given a large set of images to work with.'}]
The study used a set of high-resolution images to test the accuracy of the neural network. It found that the network performed better than expected when it was given a large set of images to work with.

Similarity score 0.6151297
Title Deep Learning Microscopy
Title   We demonstrate that a deep neural network can significantly improve optical
microscopy, enhancing its spatial resolution over a large field-of-view and
depth-of-field. After its training, the only input to this network is an image
acquired using a regular optical microscope, without any changes to its design.
We blindly tested this deep learning approach using various tissue samples that
are imaged with low-resolution and wide-field systems, where the network
rapidly outputs an image with rema

[{'summary_text': 'We demonstrate that a deep neural network can significantly improve opticalmicroscopy. After its training, the only input to this network is an imageacquired using a regular optical microscope, without any changes to its design. These results are transformative for various fields that use microscopy tools.'}]
We demonstrate that a deep neural network can significantly improve opticalmicroscopy. After its training, the only input to this network is an imageacquired using a regular optical microscope, without any changes to its design. These results are transformative for various fields that use microscopy tools.

In [60]:
pip install keybert

Collecting keybert
  Downloading keybert-0.9.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from keybert) (2.0.2)
Requirement already satisfied: rich>=10.4.0 in /usr/local/lib/python3.12/dist-packages (from keybert) (13.9.4)
Requirement already satisfied: scikit-learn>=0.22.2 in /usr/local/lib/python3.12/dist-packages (from keybert) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.3.8 in /usr/local/lib/python3.12/dist-packages (from keybert) (5.6.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.4.0->keybert) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.4.0->keybert) (2.20.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.2->keybert) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.2->keybert) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.2->keybert) (3.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert) (4.46.3)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert) (0.36.2)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert) (2.11.0+cpu)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert) (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert) (3.29.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert) (1.5.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert) (2.32.4)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.4.0->keybert) (0.1.2)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (2025.11.3)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (0.20.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (0.8.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.3.8->keybert) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.3.8->keybert) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert) (2026.6.17)
Downloading keybert-0.9.0-py3-none-any.whl (41 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.4/41.4 kB 2.1 MB/s eta 0:00:00
Installing collected packages: keybert
Successfully installed keybert-0.9.0

In [61]:
from keybert import KeyBERT

In [62]:
kw_model = KeyBERT(model)

In [63]:
type(kw_model)#model = SentenceTransformer("all-MiniLM-L6-v2")

keybert._model.KeyBERT

In [64]:
text=df.iloc[10466]["abstract"]
keywords = kw_model.extract_keywords(text)

In [65]:
print(keywords)

[('imaging', 0.4528), ('tomographic', 0.4488), ('reconstruction', 0.3623), ('deep', 0.3003), ('learning', 0.2622)]

In [66]:
print(type(keywords))

<class 'list'>

In [86]:
keywords=kw_model.extract_keywords(text, keyphrase_ngram_range=(1,2), stop_words="english")

In [87]:
print(keywords)

[('imaging deep', 0.5919), ('medical imaging', 0.5281), ('tomographic imaging', 0.525), ('image reconstruction', 0.5095), ('imaging', 0.4528)]

Additional Works-
It also tell about the entity or information of the important keywords by using Name Entity recognizers[NER].
But the problem is that NER is trained on generic dataset and it doesn't not know about the technical words like what is pytorch, and python, deeplearning and all that why i want that my model is also told about every important word that is show in keyword.

#Self work
## To find the definition, category, importance, application, related work for the entity or for the keywords.
##We use GEMINI_API_Key

In [88]:
!pip install -q google-generativeai

In [89]:
import json
import time
import google.generativeai as genai

In [96]:
GEMINI_API_KEY = "Your Key"

genai.configure(api_key=GEMINI_API_KEY)

model = genai.GenerativeModel("gemini-2.5-flash")

In [91]:
keywords

[('imaging deep', 0.5919),
 ('medical imaging', 0.5281),
 ('tomographic imaging', 0.525),
 ('image reconstruction', 0.5095),
 ('imaging', 0.4528)]

In [92]:
keyword_list = [k[0] for k in keywords]

print(keyword_list)

['imaging deep', 'medical imaging', 'tomographic imaging', 'image reconstruction', 'imaging']

In [93]:
def explain_keyword(keyword):

    prompt = f"""
You are an AI Research Assistant.

Explain the following technical keyword extracted from a research paper.

Keyword:
{keyword}

Return ONLY valid JSON.

{{
    "entity":"",
    "category":"",
    "definition":"",
    "importance":"",
    "applications":[],
    "related_terms":[]
}}
"""

    response = model.generate_content(prompt)

    try:
        text = response.text.strip()

        if text.startswith("```json"):
            text = text.replace("```json","").replace("```","").strip()

        return json.loads(text)

    except Exception:

        return {
            "entity": keyword,
            "category": "Unknown",
            "definition": response.text
        }

In [94]:
entity_information = []

for word in keyword_list:

    print(f"Processing : {word}")

    try:

        info = explain_keyword(word)

        entity_information.append(info)

        time.sleep(2)

    except Exception as e:

        print(e)

Processing : imaging deep
Processing : medical imaging

ERROR:tornado.access:503 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 3487.99ms

Processing : tomographic imaging
Processing : image reconstruction
Processing : imaging

In [95]:
from pprint import pprint

for entity in entity_information:

    pprint(entity)

    print("-"*80)

{'applications': ['**Biomedical Diagnostics and Research**: Early detection of '
                  'deep-seated tumors, neurological imaging (e.g., functional '
                  'brain imaging), cardiovascular imaging, and guiding '
                  'minimally invasive surgical procedures.',
                  '**Neuroscience**: Visualizing neuronal activity, synaptic '
                  'connections, and brain structures deep within the cortex of '
                  'living animals.',
                  '**Materials Science and Engineering**: Non-destructive '
                  'testing and evaluation (NDT/NDE) of internal defects '
                  '(cracks, voids), structural integrity analysis, and '
                  'characterization of advanced composite materials.',
                  '**Drug Discovery and Development**: Tracking drug delivery '
                  'and interaction with target cells or tissues deep within '
                  'biological models.',
                  '**Environmental and Security Applications**: Subsurface '
                  'geological mapping, through-barrier imaging for '
                  'surveillance, and deep-sea exploration.'],
 'category': 'Advanced Imaging Techniques',
 'definition': "''Imaging deep'' refers to the scientific and technological "
               'endeavor of visualizing structures or phenomena located at '
               'significant depths within opaque, turbid, or scattering media, '
               'such as biological tissues (e.g., brain, organs), complex '
               'materials, or dense environments. This field focuses on '
               'developing and applying advanced imaging modalities and '
               'computational techniques to overcome the challenges posed by '
               'light scattering, absorption, and other signal attenuation '
               'mechanisms that typically limit penetration depth and image '
               'resolution in conventional imaging methods. The ultimate goal '
               'is to achieve high-resolution, high-contrast visualization '
               'deep within a sample or organism, beyond superficial layers.',
 'entity': 'imaging deep',
 'importance': "The ability to 'image deep' is crucial for non-invasive "
               'diagnostics and treatment guidance in medicine, enabling early '
               'detection of diseases (e.g., deep-seated tumors, neurological '
               'disorders) and monitoring of therapeutic efficacy. In '
               'fundamental biological research, it provides unprecedented '
               'insights into complex biological processes and cellular '
               'functions within living organisms. Furthermore, in materials '
               'science and engineering, it facilitates non-destructive '
               'evaluation of internal structures and defects, ensuring '
               'product quality and safety across various industries.',
 'related_terms': ['Deep tissue imaging',
                   'Optical Coherence Tomography (OCT)',
                   'Multiphoton Microscopy (MPM)',
                   'Photoacoustic Imaging (PAI)',
                   'Diffuse Optical Tomography (DOT)',
                   'Light-sheet microscopy (LSM)',
                   'Adaptive Optics',
                   'Tissue Clearing',
                   'Computational Imaging',
                   'Ultrasound Imaging',
                   'Magnetic Resonance Imaging (MRI)']}
--------------------------------------------------------------------------------
{'applications': ['Diagnosis of a wide range of conditions including '
                  'fractures, tumors, infections, cardiovascular diseases, and '
                  'neurological disorders.',
                  'Monitoring disease progression and treatment effectiveness '
                  '(e.g., tumor response to chemotherapy).',
                  'Guiding interventional procedures such as biopsies, '
                  'catheter placements, and minimally invasive surgeries.',
                  'Pre-surgical planning to visualize anatomy and pathology.',
                  'Screening for certain diseases (e.g., mammography for '
                  'breast cancer, CT for lung cancer).',
                  'Assessing organ function and blood flow (e.g., nuclear '
                  'medicine scans).',
                  'Medical research and drug development to understand '
                  'biological processes and evaluate new treatments.'],
 'category': 'Diagnostic Technology',
 'definition': 'Medical imaging refers to a collection of techniques and '
               'processes used to create visual representations of the '
               'interior of a body for clinical analysis and medical '
               "intervention. It enables healthcare professionals to 'look "
               "inside' the body non-invasively or minimally invasively to "
               'diagnose, monitor, or treat disease, as well as to study '
               'normal anatomy and physiology.',
 'entity': 'medical imaging',
 'importance': 'Medical imaging is fundamental to modern healthcare, playing a '
               'crucial role in early disease detection, accurate diagnosis, '
               'precise treatment planning, and effective monitoring of '
               'various medical conditions. It reduces the need for '
               'exploratory surgeries, improves patient outcomes, and guides '
               'interventional procedures and therapies, significantly '
               'enhancing the quality and safety of patient care.',
 'related_terms': ['X-ray (Radiography)',
                   'Magnetic Resonance Imaging (MRI)',
                   'Computed Tomography (CT Scan)',
                   'Ultrasound (Sonography)',
                   'Positron Emission Tomography (PET Scan)',
                   'Nuclear Medicine',
                   'Radiology',
                   'Image Processing',
                   'Artificial Intelligence in Healthcare',
                   'Biomedical Engineering']}
--------------------------------------------------------------------------------
{'applications': ['Medical Diagnostics (e.g., X-ray Computed Tomography (CT) '
                  'for bones/organs, Magnetic Resonance Imaging (MRI) for soft '
                  'tissues, Positron Emission Tomography (PET) and '
                  'Single-Photon Emission Computed Tomography (SPECT) for '
                  'functional imaging, Ultrasound Tomography)',
                  'Non-Destructive Testing (NDT) and Material Science (e.g., '
                  'inspection of industrial components for defects, analysis '
                  'of composite materials, geological sample analysis)',
                  'Security Screening (e.g., airport baggage scanners, cargo '
                  'inspection)',
                  'Archaeology and Paleontology (e.g., visualizing ancient '
                  'artifacts or fossils without damage)',
                  'Geophysics (e.g., seismic tomography for subsurface imaging '
                  'of the Earth)',
                  'Biology and Preclinical Research (e.g., micro-CT for small '
                  'animal imaging, optical coherence tomography (OCT) for '
                  'tissue microscopy)'],
 'category': 'Imaging Technology / Diagnostic Imaging',
 'definition': 'Tomographic imaging is a technique used to create detailed '
               'cross-sectional (2D slices) or three-dimensional (3D) images '
               "of an object's internal structure. It operates by acquiring "
               'multiple two-dimensional projection measurements (e.g., '
               'X-rays, sound waves, radiofrequency signals, light) from '
               'various angles around the object. These projections are then '
               'computationally processed using sophisticated algorithms '
               '(e.g., filtered back-projection, iterative reconstruction '
               'based on the Radon transform) to reconstruct the internal '
               'density distribution or other physical properties, effectively '
               "visualizing 'slices' (tomograms) without physical dissection.",
 'entity': 'tomographic imaging',
 'importance': 'Its importance lies in its ability to non-invasively visualize '
               'the internal structures of objects, providing detailed '
               'anatomical, material, or functional information that is '
               'inaccessible by external observation. This capability is '
               'critical for accurate diagnosis, non-destructive testing, '
               'scientific research, and quality control across diverse '
               'fields, enabling early detection of diseases, analysis of '
               'material defects, and fundamental understanding of complex '
               'structures.',
 'related_terms': ['Computed Tomography (CT)',
                   'Magnetic Resonance Imaging (MRI)',
                   'Positron Emission Tomography (PET)',
                   'Single-Photon Emission Computed Tomography (SPECT)',
                   'Ultrasound Imaging',
                   'Optical Coherence Tomography (OCT)',
                   'Image Reconstruction',
                   'Radon Transform',
                   'Projection',
                   'Voxel',
                   'Slice']}
--------------------------------------------------------------------------------
{'applications': ['Medical Imaging (e.g., Computed Tomography (CT), Magnetic '
                  'Resonance Imaging (MRI), Positron Emission Tomography '
                  '(PET), Single-Photon Emission Computed Tomography (SPECT), '
                  'Ultrasound)',
                  'Astronomy (e.g., radio interferometry, aperture synthesis, '
                  'reconstruction of obscured objects)',
                  'Microscopy (e.g., electron tomography, super-resolution '
                  'microscopy, light field microscopy)',
                  'Non-Destructive Testing (NDT) (e.g., industrial CT scanning '
                  'for material inspection)',
                  'Geophysics (e.g., seismic imaging for subsurface '
                  'exploration)',
                  'Security Imaging (e.g., X-ray baggage scanners, body '
                  'scanners)',
                  'Computational Photography (e.g., light field '
                  'reconstruction, plenoptic imaging, holographic imaging)',
                  'Computer Vision (e.g., 3D reconstruction from multiple 2D '
                  "views, though often termed '3D reconstruction' or "
                  "'structure from motion')"],
 'category': 'Technique/Field of Study',
 'definition': 'Image reconstruction is the computational process of creating '
               'a visual representation (an image) of an object or scene from '
               'a set of indirect measurements or projections. This often '
               'involves solving an inverse problem, where the goal is to '
               'infer the underlying object properties from observed data that '
               'has been transformed or degraded in some way by the imaging '
               'system. The measurements are typically not directly an image '
               'but rather data collected from various angles, frequencies, or '
               'other physical phenomena that encode information about the '
               "object's internal structure or properties.",
 'entity': 'image reconstruction',
 'importance': 'Image reconstruction is critical in numerous scientific, '
               'medical, and industrial fields because it enables '
               'visualization of phenomena or structures that cannot be '
               'directly observed. It underpins non-invasive diagnostic tools, '
               'allows for imaging beyond the visible spectrum, and is '
               'essential for extracting meaningful information from complex '
               'sensor data. Advances in image reconstruction algorithms '
               'directly lead to improvements in image quality (resolution, '
               'contrast), reduced scan times, lower radiation doses, and the '
               'development of entirely new imaging modalities.',
 'related_terms': ['Inverse Problem',
                   'Tomography',
                   'Signal Processing',
                   'Image Processing',
                   'Filtered Back Projection (FBP)',
                   'Iterative Reconstruction',
                   'Compressed Sensing',
                   'Deep Learning (for reconstruction)',
                   'Sampling Theory',
                   'Fourier Transform',
                   'Point Spread Function (PSF)',
                   'Medical Imaging']}
--------------------------------------------------------------------------------
{'applications': ['Medical Diagnosis (e.g., MRI, CT scans, X-rays, Ultrasound, '
                  'PET scans for disease detection and monitoring)',
                  'Biological Research (e.g., light microscopy, electron '
                  'microscopy, fluorescence imaging for cellular and molecular '
                  'studies, fMRI for brain activity)',
                  'Materials Science (e.g., scanning electron microscopy, '
                  'transmission electron microscopy, atomic force microscopy '
                  'for material characterization)',
                  'Remote Sensing (e.g., satellite imaging for Earth '
                  'observation, environmental monitoring, urban planning)',
                  'Astronomy (e.g., optical, radio, X-ray telescopes for '
                  'studying celestial objects and phenomena)',
                  'Industrial Inspection and Non-Destructive Testing (e.g., '
                  'X-ray imaging for defect detection in manufacturing)',
                  'Security Screening (e.g., airport baggage scanners, thermal '
                  'imaging for surveillance)',
                  'Geophysics (e.g., seismic imaging for subsurface '
                  'exploration)'],
 'category': 'Methodology',
 'definition': 'Imaging refers to the process of creating visual '
               'representations (images) of an object, phenomenon, or system. '
               'This often involves using various forms of energy (e.g., '
               'electromagnetic radiation like X-rays, visible light, '
               'infrared, radio waves; sound waves; particles like electrons) '
               'and specialized detectors to acquire data, which is then '
               'processed and reconstructed into an interpretable visual '
               'output. The primary goal is to visualize structures, '
               'functions, or processes that are not directly observable by '
               'the human eye, or to capture and analyze visual information in '
               'a structured and quantifiable manner.',
 'entity': 'imaging',
 'importance': 'Imaging is a cornerstone of modern scientific research and '
               'technology due to its unparalleled ability to provide '
               'non-invasive or minimally invasive insights into the internal '
               'structure, function, and composition of diverse systems. It '
               'enables detailed visualization of microscopic to macroscopic '
               'scales, detection of subtle changes, quantitative measurement '
               'of parameters, and monitoring of dynamic processes, all '
               'crucial for discovery, diagnosis, quality control, and '
               'understanding complex phenomena across various fields.',
 'related_terms': ['Medical Imaging',
                   'Microscopy',
                   'Tomography',
                   'Spectroscopy',
                   'Image Processing',
                   'Computer Vision',
                   'Modality (imaging)',
                   'Signal Processing',
                   'Visualization',
                   'Radiography']}
--------------------------------------------------------------------------------

In [84]:
with open("paper_entities.json","w",encoding="utf-8") as f:

    json.dump(entity_information,
              f,
              indent=4,
              ensure_ascii=False)

print("Saved Successfully")

Saved Successfully

In [85]:
import pandas as pd

df = pd.DataFrame(entity_information)

df

,entity,category,definition,importance,applications,related_terms
0,Tomographic Imaging Deep,"Medical Imaging, Image Reconstruction, Machine...",Tomographic imaging deep refers to the integra...,The application of deep learning to tomographi...,[Medical Computed Tomography (CT): Low-dose CT...,"[Deep Learning Reconstruction, AI in Medical I..."
1,imaging deep learning,Methodology / Interdisciplinary Field,Imaging deep learning refers to the applicatio...,Imaging deep learning has revolutionized numer...,"[Medical Imaging: Disease detection (e.g., can...","[Deep Learning, Machine Learning, Computer Vis..."
2,learning medical imaging,Interdisciplinary Field / Application Area of AI,Learning medical imaging refers to the applica...,This field is crucial for advancing healthcare...,"[Disease Detection and Classification (e.g., i...","[Deep Learning for Medical Imaging, Medical Im..."
3,Imaging Deep,"Artificial Intelligence, Machine Learning, Com...",'Imaging Deep' refers to the application of de...,The importance of 'Imaging Deep' stems from it...,"[**Medical Imaging**: Disease diagnosis (e.g.,...","[Deep Learning, Convolutional Neural Networks ..."
4,medical imaging,Healthcare Technology / Diagnostics,Medical imaging refers to various techniques a...,Medical imaging is fundamental to modern healt...,"[Disease diagnosis (e.g., detecting tumors, fr...","[Radiology, X-ray (Radiography), Computed Tomo..."

Next class-
LLM
Langchain
Tools
RAG

##NLP DONE

# Project 3-> Agentic AI

In [69]:
!pip install langchain-community

Collecting langchain-community
  Downloading langchain_community-0.4.2-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (3.14.1)
Collecting httpx-sse<1.0.0,>=0.4.0 (from langchain-community)
  Downloading httpx_sse-0.4.3-py3-none-any.whl.metadata (9.7 kB)
Collecting langchain-classic<2.0.0,>=1.0.7 (from langchain-community)
  Downloading langchain_classic-1.0.8-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (1.4.8)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.9.1)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.2)
Collecting pydantic-settings<3.0.0,>=2.10.1 (from langchain-community)
  Downloading pydantic_settings-2.14.2-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (6.0.3)
Collecting requests<3.0.0,>=2.32.5 (from langchain-community)
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.51)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (9.1.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.5.2)
Requirement already satisfied: typing_extensions>=4.4 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (4.15.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.24.2)
Collecting langchain-text-splitters<2.0.0,>=1.1.2 (from langchain-classic<2.0.0,>=1.0.7->langchain-community)
  Downloading langchain_text_splitters-1.1.2-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-classic<2.0.0,>=1.0.7->langchain-community) (2.13.4)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain-community) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain-community) (0.0.18)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain-community) (26.2)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain-community) (0.16.2)
Requirement already satisfied: anyio>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (4.14.0)
Requirement already satisfied: distro>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.11.9)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.3.1)
Requirement already satisfied: websockets>=15.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (15.0.1)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.7.1)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.25.0)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.2.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2026.6.17)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3.0.0,>=1.4.0->langchain-community) (3.5.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.4.0->langchain-community) (3.1.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.7->langchain-community) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.7->langchain-community) (2.46.4)
Downloading langchain_community-0.4.2-py3-none-any.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 18.4 MB/s eta 0:00:00
Downloading httpx_sse-0.4.3-py3-none-any.whl (9.0 kB)
Downloading langchain_classic-1.0.8-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 38.3 MB/s eta 0:00:00
Downloading pydantic_settings-2.14.2-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 2.3 MB/s eta 0:00:00
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 3.3 MB/s eta 0:00:00
Downloading langchain_text_splitters-1.1.2-py3-none-any.whl (35 kB)
ERROR: Operation cancelled by user

KeyboardInterrupt:

In [ ]:
!pip install langchain_core

In [ ]:
from langchain_core.tools import tool

In [ ]:
@tool
def search_paper(query:str)-> str:
  "Search research paper from the faiss database and retun the most relevant result"

In [ ]:
!pip install langchain-huggingface

In [ ]:
from langchain_huggingface import HuggingFacePipeline

In [ ]:
llm = HuggingFacePipeline(pipeline=summarizer)

In [ ]:
llm

In [ ]:
response =llm.invoke("ABSTRACTNow a day’s recommendation system has changed the style ofsearching the things of our interest. This is information filtering approach that is used to predict the preference of thatuser.The most popular areas where recommender system is appliedare books, news, articles, music, videos, movies etc. In thispaper we have proposed a movie recommendation systemnamed MOVREC. It is based on collaborative filteringapproach that makes use of the information provided by users,analyzes them and then recommends the movies that is bestsuited to the user at that time. The recommended movie list issorted according to the ratings given to these movies byprevious users and it uses K-means algorithm for this purpose.MOVREC also help users to find the movies of their choicesbased on the movie experience of other users in efficient andeffective manner without wasting much time in uselessbrowsing. This system has been developed in PHP usingDreamweaver 6.0 and Apache Server 2.0. The presentedrecommender system generates recommendations usingvarious types of knowledge and data about users, the availableitems, and previous transactions stored in customizeddatabases. The user can then browse the recommendationseasily and find a movie of their choice.KeywordsK-means, recommendation system, recommender system, datamining, clustering, movies, Collaborative filtering, Contentbased filtering")

In [ ]:
print(response)

In [ ]:
print(type(response))